apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webapp-secret
  namespace: production
spec:
  encryptedData:
    DB_PASSWORD: AQICAHjotC7sJH9xLb4DYQkz4Y3mBL2KLTnZ/1aZqz1JcGKpYp0D5lZ6gPmA4FxQShkJ6n8yPz9scV9QYg3M1tUdLqv26M1DXY0LZtG5x7vEwYzJ+gAAAAjDCBrQYJKoZIhvcNAQcGoIGYMIGVAgEAMIGXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDG4/OL5FcgM3VQgDMhAIBEICvS5B9nV4z5uSVxA8L6GQHiB8H2hPVdW66X36GbWV1I2AnJuQtQmRQ==
    API_KEY: AQICAHju4ieL8kExdHVN6ko3HwZl0o+st6J6m1+2pH4OzS9ucvNRs3XwZpK8yxY78w4NC6HqvLRT0v5U2Q==
  template:
    metadata:
      name: webapp-secret
      namespace: production
