apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webapp-secret
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AQICAHjztkUpr3Y6kTg3MU9YcDBVg2kl4gOeLzjaSzlGj5Cg4Qtq4okVaaiZNtM7tZb/7dYGxAAAAjDCBqQYJKoZIhvcNAQcGoIGeMIGbAgEAMIGXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDM/a8kPZ2sH4X-UezQIBEIBWmVUdVv1A9iyzHhPIaO-9X9z3dA8Ue8hU0ZDV7Qk8eKLx2QpRAAWg2g==
    API_KEY: AQICAHjzkFyXLGkR6lEcv7gU7KpeVhMXd2Q48la5CwDgQh8T1gxz1AgkK0n9wfWJHpUz9mQO2RaSx5SgkoiM7uHU2kL0ntxwXONaIZpHnK1XuXvYq4AAAAqjCCAzYwggMrBgkqhkiG9w0BBwaggjswggI6AgEAMIGwBgkqhkiG9w0BBwaggYgwgYMg
  template:
    metadata:
      name: webapp-secret
      namespace: staging
